### ISSUE TITLE
how to zoom in application ?

### ISSUE THREAD

**Issue by dvi7ik** [dangeredwolf/ModernDeck#173] opened 2020-11-22 18:24 UTC
window user
lot of unnecessary empty space.
i can't zoom  in application window 8.1 (https://user-images.githubusercontent.com/66706128/99912738-c0fc6500-2d1d-11eb-85ae-b2ef97534711.PNG)

**Comment by dangeredwolf** [comment] 2020-12-11 06:40
Hello! The latest version of ModernDeck is ModernDeck 9.0. Does the issue still occur there? I'd be happy to help.

**Comment by dangeredwolf** [comment] 2020-12-11 06:47
Upon further inspection, it looks like you're using a custom CSS stylesheet that changes how ModernDeck looks. Does this still occur without it?

**Comment by dangeredwolf** [comment] 2021-01-04 21:43
I'm closing this issue because it seems to be an issue with your custom CSS stylesheet. If you can reproduce this issue without a custom CSS stylesheet, please let me know and I will reopen the issue.

**Closed by dangeredwolf** 2021-01-04 21:43 UTC
Labels: bug, cannot reproduce/invalid
