### ISSUE TITLE
AMOLED theme is unusable in "Light" design from tweetdeck

### ISSUE THREAD

**Issue by derN3rd** [dangeredwolf/ModernDeck#86] opened 2016-06-22 09:35 UTC
Just try it out, you cannot read text. And everything is darker than my ex's heart...

Maybe you can automatically switch the tweetdeck themes before switching designs!

**Comment by ciolt** [comment] 2016-06-27 00:27
Due to the way themes work in ModernDeck, it's not possible at the moment to make the themes switch between Light/Dark by themselves. The only way to do it would be to override the light theme's code, but that would simply overcomplicate things.

I'll see if I can make the themes be controlled by JavaScript using templating, but since it's a "minor" issue I don't guarantee that I or @dangeredwolf will have it fixed for the next release.

**Comment by dangeredwolf** [comment] 2016-10-17 16:51
Well said, @ciolt. 

ModernDeck 6.0 and later implements the new theme system allowing for styles to be separated into different files, which reduces memory footprint and reduces the amount of rules required: Something that the new themes system really needed in order to run well.

The problem is a fundamental one: You can enable the AMOLED theme while the light theme is active. The themes system I've implemented is really good at stacking. For example stacking base moderndeck.css, with dark.css on top, with amoled.css on top, with scrollbarsnone.css on top, with hearts.css on top. However, swap that dark.css with light.css, and it's not designed for each other, but it does the best it can to adapt and apply itself to the page.

This is something that might be fixed in 6.2. 6.1 was rushed due to multiple issues related to TweetDeck updates. But it's something we'd like to implement in the future.

**Comment by dangeredwolf** [comment] 2019-04-21 22:59
Revisiting this old issue: This is being fixed in the next major version of ModernDeck, so thus I have added the fixed tag and am closing this issue.

**Closed by dangeredwolf** 2019-04-21 22:59 UTC
Labels: bug, fixed, light theme, theme modular system
